sudo: required
dist: trusty
language: node_js
node_js:
- '8'
env:
- SOLIDITY_COVERAGE=true
install:
- npm install -g truffle
- npm install -g ethereumjs-testrpc
- npm install
script:
- npm test
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
notifications:
  slack:
    secure: QiB918+G3hHGYT2Qw5MfN9gDh+V2Zj6perenormZNC1uD5RmkpqfUitHdbXvseUnGmgN2G0M05j6jSpDQf21BkJX+/x92io6Zm0Dzvx5dXNC39cJFGaEhJmPjhYstbpnadysji2qQ7E+UMo7MewnlFMfuQQOywH11RBgpCBYy0ZCy/8VkN2xV15RAI1ISNBQHZ+z8F05wk+J1OOftQpBtyjZRuhbF3efwZmpRA8lyVoMPuCppZ0JfDGHewKbNqtBIC2zDjS3UgOpKLm7Y5yQ1m8epS+N1E3m8SI2pkYbZvURTKlD0Ip0FAqzAf+UOAgePzYmHH88qYPd6M3NM6JdnveLF3w58VWLriFYbIuffyW6iJHnp2APXy0lsBAd4ezFnviucrKHFfGC17he38dIovos/xBZlTHOGfaKmRwHxnS3ZK80KjGRc0Fivq9pjHWu67qXDLeKQLB/Rm3h5dozPdUVWzdq/bj224AYLlJAVb4Q4l/InLRedJpvZWW6rblsLo/JgePK/IP9tzKSvamUxvt9luWoxVgPn0toR8fJ5hxVZL5hmeZslgsD76olayNnQbvf6zRhi7n71S22sKJVwazfxg3UTHRMllRmOmB3czjhmCQRMab3Ez9aO9JKfAznwkV5IcLTB7VXFVeFMl53EUh6+tnNtzaE1DkMd62N33k=
